/**
 * Regenerates src/ocr/paddle/charset.ts from the official PP-OCRv6 rec model's
 * own config, so the character list can never drift from the weights.
 *
 * Run with: node scripts/extract-charset.mjs
 *
 * The list is not published as a standalone file anywhere official — it lives
 * inline in `inference.yml` next to the model on Hugging Face. Third-party
 * copies of the dictionary exist and are what most ports use; taking it from
 * the model's own config instead means the two cannot disagree.
 */
import { writeFileSync } from "node:fs";

const REC_CONFIG =
  "https://huggingface.co/PaddlePaddle/PP-OCRv6_small_rec_onnx/resolve/main/inference.yml";
const OUTPUT = new URL("../src/ocr/paddle/charset.ts", import.meta.url);

/** Unquotes the handful of entries YAML had to quote, such as ':' and ''''. */
function unquote(value) {
  if (value.startsWith("'") && value.endsWith("'") && value.length >= 2) {
    return value.slice(1, -1).replaceAll("''", "'");
  }
  if (value.startsWith('"') && value.endsWith('"') && value.length >= 2) {
    return JSON.parse(value);
  }
  return value;
}

const yaml = await fetch(REC_CONFIG).then((response) => {
  if (!response.ok) {
    throw new Error(`${response.status} fetching ${REC_CONFIG}`);
  }
  return response.text();
});

const marker = "  character_dict:\n";
const start = yaml.indexOf(marker);
if (start === -1) {
  throw new Error("character_dict not found in the model config");
}

const entries = [];
for (const line of yaml.slice(start + marker.length).split("\n")) {
  if (!line.startsWith("  - ")) {
    if (line.trim() === "") continue;
    break;
  }
  entries.push(unquote(line.slice(4)));
}

// PaddleOCR's CTCLabelDecode builds its label list as
// ["blank", ...character_dict, " "], so the model's class count is the dict
// length plus two. Anything else here means the parse went wrong or the model
// changed — which is exactly what this caught on the move from v5 to v6.
//
// The number is not taken on trust: it is the shape of the final linear layer's
// bias in the graph's own `inference.json` (`linear_8.b_0`, `[18710]`). A dict
// that decodes against the wrong number of classes does not fail, it returns
// plausible nonsense.
const EXPECTED_CLASSES = 18710;
if (entries.length + 2 !== EXPECTED_CLASSES) {
  throw new Error(
    `parsed ${entries.length} entries, which makes ${entries.length + 2} classes, not ${EXPECTED_CLASSES}`,
  );
}

const body = `/**
 * Generated by scripts/extract-charset.mjs from the official PP-OCRv6 small rec
 * config. Do not edit by hand.
 *
 * Source: ${REC_CONFIG}
 */

/**
 * The recognizer's label list, in the order PaddleOCR's CTCLabelDecode builds
 * it: a blank at index 0, then the model's own dictionary, then a space. Its
 * length is exactly the rec graph's output class count.
 */
export const CHARSET: readonly string[] = [
  "",
  ${JSON.stringify(entries).slice(1, -1)},
  " ",
];

/** CTC blank. Index 0 by construction, never a real character. */
export const BLANK_INDEX = 0;
`;

writeFileSync(OUTPUT, body);
console.log(`wrote ${entries.length + 2} labels to src/ocr/paddle/charset.ts`);
