/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardBoardSlugRouteImport } from './routes/board.$boardSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardSlugRoute = BoardBoardSlugRouteImport.update({
  id: '/board/$boardSlug',
  path: '/board/$boardSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board/$boardSlug': typeof BoardBoardSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board/$boardSlug': typeof BoardBoardSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board/$boardSlug': typeof BoardBoardSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/board/$boardSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/board/$boardSlug'
  id: '__root__' | '/' | '/board/$boardSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardBoardSlugRoute: typeof BoardBoardSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardSlug': {
      id: '/board/$boardSlug'
      path: '/board/$boardSlug'
      fullPath: '/board/$boardSlug'
      preLoaderRoute: typeof BoardBoardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardBoardSlugRoute: BoardBoardSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
